/**
 * Tailwind preset for the component library.
 *
 * Customize design tokens in `src/css/variables/` and extend this preset
 * in your app's `tailwind.config.js`.
 *
 * Utilities are prefixed with `ds-` when consumed as a library preset
 * (local Storybook uses an empty prefix via tailwind.config.js).
 */

const semanticColors = {
  base: {
    bg: 'var(--base-bg)',
    fg: 'var(--base-fg)',
    border: 'var(--base-border)',
    text: 'var(--base-text)',
    'para-text-color': 'var(--base-para-text-color)',
    icon: 'var(--base-icon)',
    link: 'var(--base-link)',
    'heading-text-color': 'var(--base-heading-text-color)',
    'sub-text-color': 'var(--base-sub-text-color)',
    'light-text-color': 'var(--base-light-text-color)',
  },
  action: {
    'primary-default': 'var(--action-primary-default)',
    'primary-hover': 'var(--action-primary-hover)',
    'primary-press': 'var(--action-primary-press)',
    'primary-disable': 'var(--action-primary-disable)',
    'primary-text': 'var(--action-primary-text)',
    'primary-text-disable': 'var(--action-primary-text-disable)',
    'secondary-default': 'var(--action-secondary-default)',
    'secondary-hover': 'var(--action-secondary-hover)',
    'secondary-press': 'var(--action-secondary-press)',
    'secondary-disable': 'var(--action-secondary-disable)',
    'secondary-text': 'var(--action-secondary-text)',
    'secondary-text-disable': 'var(--action-secondary-text-disable)',
    'neutral-default': 'var(--action-neutral-default)',
    'neutral-hover': 'var(--action-neutral-hover)',
    'neutral-press': 'var(--action-neutral-press)',
    'neutral-disable': 'var(--action-neutral-disable)',
    'neutral-text': 'var(--action-neutral-text)',
    'neutral-disable-text': 'var(--action-neutral-disable-text)',
    'ghost-default': 'var(--action-ghost-default)',
    'ghost-border': 'var(--action-ghost-border)',
    'ghost-hover': 'var(--action-ghost-hover)',
    'ghost-press': 'var(--action-ghost-press)',
    'ghost-disable': 'var(--action-ghost-disable)',
    'ghost-text': 'var(--action-ghost-text)',
    'ghost-text-disable': 'var(--action-ghost-text-disable)',
    'success-default': 'var(--action-success-default)',
    'success-hover': 'var(--action-success-hover)',
    'success-press': 'var(--action-success-press)',
    'success-text': 'var(--action-success-text)',
    'warning-default': 'var(--action-warning-default)',
    'warning-hover': 'var(--action-warning-hover)',
    'warning-press': 'var(--action-warning-press)',
    'warning-text': 'var(--action-warning-text)',
    'error-default': 'var(--action-error-default)',
    'error-hover': 'var(--action-error-hover)',
    'error-press': 'var(--action-error-press)',
    'error-text': 'var(--action-error-text)',
  },
  form: {
    text: 'var(--form-text)',
    placeholder: 'var(--form-placeholder)',
    border: 'var(--form-border)',
    selected: 'var(--form-selected)',
    hover: 'var(--form-hover)',
    error: 'var(--form-error)',
    success: 'var(--form-success)',
    'error-bg': 'var(--form-error-bg)',
    disable: 'var(--form-disable)',
    'selected-color': 'var(--form-selected-color)',
    'disable-selected': 'var(--form-disable-selected)',
    'disable-text': 'var(--form-disable-text)',
  },
  feedback: {
    'default-bg': 'var(--feedback-default-bg)',
    'default-text': 'var(--feedback-default-text)',
    'default-cross': 'var(--feedback-default-cross)',
    'error-bg': 'var(--feedback-error-bg)',
    'error-text': 'var(--feedback-error-text)',
    'error-cross': 'var(--feedback-error-cross)',
    'info-bg': 'var(--feedback-info-bg)',
    'info-text': 'var(--feedback-info-text)',
    'info-cross': 'var(--feedback-info-cross)',
    'success-bg': 'var(--feedback-success-bg)',
    'success-text': 'var(--feedback-success-text)',
    'success-cross': 'var(--feedback-success-cross)',
    'warning-bg': 'var(--feedback-warning-bg)',
    'warning-text': 'var(--feedback-warning-text)',
    'warning-cross': 'var(--feedback-warning-cross)',
  },
  cards: {
    bg: 'var(--cards-bg)',
    hover: 'var(--cards-hover)',
    text: 'var(--cards-text)',
    border: 'var(--cards-border)',
    icon: 'var(--cards-icon)',
    link: 'var(--cards-link)',
  },
  'other-clickable': 'var(--color-other-clickable)',
};

export const tailwindPreset = {
  darkMode: 'class',
  prefix: 'ds-',
  theme: {
    extend: {
      colors: {
        ...semanticColors,
        dark: semanticColors,
      },
      fontSize: {
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        4.5: '1.125rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
      },
      lineHeight: {
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
      },
      boxShadow: {
        e100: '0px 0px 1px 0px rgba(9, 30, 66, 0.31), 0px 1px 1px 0px rgba(9, 30, 66, 0.25)',
        e200: '0px 0px 1px 0px rgba(9, 30, 66, 0.31), 0px 3px 5px 0px rgba(9, 30, 66, 0.20)',
        e300: '0px 0px 1px 0px rgba(9, 30, 66, 0.31), 0px 8px 12px 0px rgba(9, 30, 66, 0.15)',
      },
    },
  },
  plugins: [],
};
